title: 'BitDevsKLA'
tagline: 'BitDevsKLA is a monthly meetup devoted to the research and development of Bitcoin'

menu:
  - {name: 'Events', url: '/events'}
  - {name: 'Luma', url: 'https://lu.ma/BitDevsKLA', external: true}
  - {name: 'Discord', url: '#', external: true}
  - {name: 'X', url: 'https://x.com/BitDevsKLA', external: true}
